TeeAsk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from TeeAsk import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from TeeAsk.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view()),
    url(r'^user/(?P<id>\d+)', UserPosts.as_view(), name='get user posts'),
    url(r'^login/', LoginView.as_view()),
    url(r'^register/', RegisterView.as_view()),
    url(r'^load/', LoadView.as_view()),
    url(r'^logout/', LogoutView.as_view()),
    url(r'^like/', LiveView.as_view()),
    url(r'^new_question/', NewQuestionView.as_view()),
    url(r'^question/(?P<num>\d+)', QuestionView.as_view(), name='get question'),
    url(r'^settings/', SettingsView.as_view(), name='upload_pic'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TeeAsk/models.py
from django.db import models
from django.contrib.auth.models import User, UserManager


class Profile(User):
    avatar = models.ImageField(upload_to='media', default='default.png')
    objects = UserManager()

    def __unicode__(self):
        return self.username


class Post(models.Model):
    author = models.ForeignKey(Profile, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, auto_now=False)
    title = models.TextField()
    text = models.TextField()
    answers = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Answer(models.Model):
    author = models.ForeignKey(Profile, default=None, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, auto_now=False)
    text = models.TextField()
    likes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.text

class Like(models.Model):
    user = models.ForeignKey(Profile, default=None, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __unicode__(self):
        return str(self.id)

class Tag(models.Model):
    name = models.CharField(max_length=30, default=None)

    def __unicode__(self):
        return self.name

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>

<html>

<head>
    <meta charset="utf-8">
    <title> {{ title }} </title>
    <link rel="stylesheet" type="text/css" href="../static/css/base.css?v=1.9">
    <link rel="stylesheet" type="text/css" href="../static/css/modal.css?v=1.0">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    {% block styles %}
    {% endblock %}
</head>

<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<div class="grid">
    <div>
        <a href="../../"><img src="../static/img/newlogo.png" class="logo" ></a>
        <!--<input type="text" class='search' placeholder="Мы найдём! Только попроси...">-->
        {% if user.username %}
            <button class="header-button-right"><a href="/logout">Log out</a></button>
            <button class="header-button-right" id="set_button"><a>Settings</a></button>
            <img src={{ user.avatar.url }} class="header-button-right">
        {% else %}
            <button class="header-button-right"><a href="/register">Sing up</a></button>
            <button class="header-button-right"><a href="/login">Log in</a> </button>
        {% endif %}

    </div>
    <div class='center'>
        {% block center %}
        {% endblock %}
    </div>
    <div>
        <div class='panel'>
            <div class='panel-head'>
                #Tags
            </div>
            <div class="panel-body">
                stupid questions cartoons
                games askYan
                RELATIONSHIPS
                c++
            </div>
        </div>

        <div class='panel-2'>
            <div class='panel-head-2'>
                #Cytest Members
            </div>
            <div class="panel-body">
                TheSlave Homer
                Me TheGodess
                KIM Neo Ms. Lollipop
            </div>
        </div>

        <div>

            {% if user.username %}
                <button id='qs_button' class='question-button'>Задать вопрос</button>
            {% endif %}
        </div>


    </div>
</div>
{% block scripts %}
{% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="../static/css/nqst.css?v=1.4">
{% endblock %}

{% block center %}
    <div id='thread' class='center'>
        {% for p in posts %}
            <div class="post" id="post_id-{{ p.id }}">
                <div class="post-pic">
                    <img class='post-img' src="{{ MEDIA_URL }}{{ p.author.avatar.url }}"/>
                </div>
                <div class="post-text">
                    <h2>
                        <a id='title' href="{% url 'get question' p.id %}">{{ p.title }}</a>
                    </h2>
                    <p id='post-text'>{{ p.text }}</p>
                    <p>Вопрос задан пользователем: <a id="user_anchor"
                                                      href="{% url 'get user posts' p.id %}">{{ p.author }}</a></p>
                    <p>answers ( {{ p.answers }} ) Tags: stupid questions</p>

                    <div>
                        {% if p in liked_posts %}
                            {% for l in likes %}
                                {% if l.post.id == p.id %}
                                    {% if l.value > 0 %}


                                    {% else %}

                                    {% endif %}

                                {% endif %}

                            {% endfor %}
                        {% endif %}

                        <img class="rating-img" id='like' src="../static/img/lois.png">

                        {% if p.likes >= 0 %}
                            <font id='score' size='7' color='green'>{{ p.likes }}</font>
                        {% else %}
                            <font id='score' size='7' color='red'>{{ p.likes }}</font>
                        {% endif %}

                        <img class="rating-img" id='dislike' src="../static/img/dislois.png">
                    </div>

                </div>
            </div>
        {% endfor %}
        <div id="quesModal" class="modal">
            <div class="form">
                <img class='login-img' src="../static/img/Budda.gif">
                <div class="inner">
                    <div class="tab-content">
                        <div id="login">
                            <h1></h1>
                            <form id='nq-form' method="post"> {% csrf_token %}
                                <div class="field-wrap">
                                    {{ ques_form.title }}
                                </div>
                                <div class="field-wrap">
                                    {{ ques_form.text }}
                                </div>
                                <button id='nq-button' class="button button-block"/>
                                Готово</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="settingModal" class="modal">
            <div class="form">
                <form action="{% url 'upload_pic' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <p>
                        <input id="id_image" type="file" class="" name="image">
                    </p>
                    <input type="submit" value="Выбрать аватар"/>
                </form>
                <!--<img class='login-img' src="../static/img/Magnitik.png">
                <div class="inner">
                    <div class="tab-content">
                        <div id="login">
                            <h1>Тут вы можете сменить ник и аватар</h1>
                            <form id='nq-form' method="post"> {% csrf_token %}
                                <div class="field-wrap">
                                    {{ ques_form.title }}
                                </div>
                                <div class="field-wrap">
                                    {{ ques_form.text }}
                                </div>
                                <button id='nq-button' class="button button-block"/>
                                Готово</button>
                            </form>
                        </div>
                    </div>
                </div>-->
            </div>
        </div>

    </div>
{% endblock %}


{% block scripts %}
    <script src="../static/js/modal.js?v=1.0"></script>
    <script src="../static/js/scroll.js?v=1.1"></script>
    <script>
        $('[id^="like"]').click(function () {
            let id = $(this).closest("div.post").attr("id").split('-')[1];
            $.get('/like', {'id': id, 'value': 1}, function (data) {
                var el = document.getElementById('post_id-' + data.id);
                el.querySelector('#score').innerText = data.like;
            });
        });
        $('[id^="dislike"]').click(function () {
            let id = $(this).closest("div.post").attr("id").split('-')[1];
            $.get('/like', {'id': id, 'value': -1}, function (data) {
                var el = document.getElementById('post_id-' + data.id);
                el.querySelector('#score').innerText = data.like;
            });
        });
    </script>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="../static/css/login.css?v1.0">
{% endblock %}


{% block center %}
    <div class="form">
        <img class='login-img' src="../static/img/%D0%A1%D0%B8%D0%BC.png">
        <div class="inner">
                <div id="login">
                    <br>
                    <br>
                    <h1>Welcome Back!</h1>
                    <h4>
                        {% if error %}
                            {{ error }}
                        {% endif %}
                    </h4>
                    <form method="post"> {% csrf_token %}
                        <div class="field-wrap">
							{{ login_form.username }} </div>
						<div class="field-wrap">

							{{ login_form.password }} </div>
                        <p class="forgot"><a href="#">Forgot Password?</a></p>
                        <button class="button button-block"  type="submit" name="log"/>Log In</button>

                    </form>
                </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    $("#id_username").attr('placeholder', 'Username');
    $("#id_password").attr('placeholder', 'Password');
</script>
{% endblock %}

templates/new_question.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="../static/css/nqst.css?v=1.3">
{% endblock %}

{% block center %}
    <div class="form">
        <img class='login-img' src="../static/img/Budda.gif">
        <div class="inner">
            <div class="tab-content">
                <div id="login">
                    <h1></h1>
                    <form id='nq-form' method="post"> {% csrf_token %}
                        <div class="field-wrap">
                            {{ ques_form.title }}
                        </div>
                        <div class="field-wrap">
                            {{ ques_form.text}}
                        </div>
                        <button id='nq-button' class="button button-block"/>
                        Готово</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="../static/js/index.js"></script>
    <script>
        $('#nq-form').submit(function (e) {
            e.preventDefault();
            let title = $('#id_title').val();
            let text = $('#id_text').val();

            /*$.post('/new_question/', {'title':title, 'text':text, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function (data) {
                console.log(123123);
            });*/
        });
    </script>


{% endblock %}

templates/question.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
    <link rel="stylesheet" href="../static/css/question.css?v=1.2">
{% endblock %}

{% block center %}
    <div class='center'>
        <div class="question">
            <div class="post-pic">
                <img class='post-img' src="../static/img/jc.png"/>
                <p>TeeNik</p>

            </div>
            <div class="post-text">
                <h2>
                    {{ post.title }}
                </h2>
                {{ post.text }}
                <p>Tags: stupid questions</p>

                <div>
                    <img class="rating-img" src="../static/img/lois.png">
                    <font size='7' color='red'>5</font>
                    <img class="rating-img" src="../static/img/dislois.png">
                </div>

            </div>
        </div>

        {% for a in answers %}
            <div class="answer">
                <div class="post-pic">
                    <img class='post-img' src={{ a.author.avatar.url }}/>

                </div>
                <div class="post-text">
                    <p>{{ a.author }}</p>
                    {{ a.text }}

                    <div>
                        <img class="rating-img" id='like' src="../static/img/lois.png">

                        {% if a.likes >= 0 %}
                            <font id='score' size='7' color='green'>{{ a.likes }}</font>
                        {% else %}
                            <font id='score' size='7' color='red'>{{ a.likes }}</font>
                        {% endif %}

                        <img class="rating-img" id='dislike' src="../static/img/dislois.png">
                    </div>

                </div>
            </div>
        {% endfor %}

        <div class='panel-3'>
            <div class='panel-head-3'>
                Ваше мнение безусловно важно для всех
            </div>
            <div class="panel-body">
                <form method="post"> {% csrf_token %}
                    <div class="field-wrap">
                        {{ answer_form.text }}
                    </div>
                    <button type="submit" id='ques-button' class="button button-block"/>Отправить</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="../static/css/login.css">
{% endblock %}


{% block center %}
    <div class="form">
        <img class='login-img' src="../static/img/%D0%A1%D0%B8%D0%BC.png">
        <div class="inner">
            <div id="signup">
                <h1>Sign Up for Free</h1>
                <form method="post"> {% csrf_token %}
                    <div class="field-wrap">
                        <label> Username<span class="req">*</span> </label>
                        {{ reg_form.username }}
                    </div>
                    <div class="field-wrap">
                        <label> Email Address<span class="req">*</span> </label>
                        {{ reg_form.email }} </div>
                    <div class="field-wrap">
                        <label> Set A Password<span class="req">*</span> </label>
                        {{ reg_form.password }} </div>
                    <button type="submit" class="button button-block" name="reg"/>
                    Get Started</button>
                </form>
            </div>
            <!-- tab-content -->
        </div>
    </div>
{% endblock %}

templates/setting.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="../static/css/nqst.css?v=1.2">
{% endblock %}

{% block center %}
    <div class="form">
        <img class='login-img' src="../static/img/Magnitik.png">
        <div class="inner">
            <div class="tab-content">
                <div id="login">
                    <h1></h1>
                    <form method="post"> {% csrf_token %}
                        <div class="field-wrap">
                            {{ ques_form.title }} </div>
                        <div class="field-wrap">
                            {{ ques_form.text}}</div>
                        <button class="button button-block"/>
                        Готово</button>
                    </form>
                </div>
            </div>
            <!-- tab-content -->
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="../static/js/index.js"></script>
{% endblock %}